title: "Frank <u>Matthias</u> KOVATSCH"
description: "Dr. sc. ETH Zurich â€” Internet of Things Expert"
google_analytics: 
show_downloads: false
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
